### ISSUE TITLE
Power deletion

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#1]
D - Deletes from cursor to end of line
dw – Deletes the next word.
db – Deletes the previous word
de – Deletes to the end of the current word.
dL – Deletes all text below the cursor in the file.
d/unicorn – After pressing Enter, deletes all text between the cursor and the word “unicorn” in the current file.
dd – Deletes an entire line.

**Comment by Alexey-T** [comment]
Done this

  D - delete to end of line
  dd - delete current line
  db - delete to word begin
  dw, de - delete to word end (currently commands work the same)
  dL - delete to text end

"d/str" not done yet.

2 - how dw / de must differ? I made them the same

**Comment by Alexey-T** [comment]
"d/str" -- done.
Pls test it.

**Comment by mangobait** [comment]
D works

dL works

dd works

db works

d/str works

dw and de working the same BUT not good. if you dw and want to do it a
second time, you only delete the space so must do three times to delete two
words. de should be just to end of word but not the space but dw end of
word plus next space. Also, you should be able to repeat de to delete two
words; but it still gets stuck on the space so must do three times to
delete two words.

2017-10-01 4:05 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
Thanks for this note

**Comment by Alexey-T** [comment]
"de" fixed- I tried to make like Vim, pls test.

**Comment by mangobait** [comment]
de is good; you can do two commands and delete two words

dw needs fixing; after one instance of command, it has a space in front of
it and so you need to do three times to delete two words. After once
instance of dw the cursor should be on the first character of the new word.

(this is one reason why . is such a good command; you do de once and then
hit . as many times as you need to delete more; very fast)

2017-10-05 6:14 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
@vakosel Pls test this issue. do you see it needs fixing more?

**Comment by vakosel** [comment]
I will let you know when I get back home.. 
--
Sent from Outlook Email App for Android Tuesday, 08 January 2019, 11:28AM +02:00 from Alexey  notifications@github.com :

**Comment by vakosel** [comment]
It works fine . I tested your visual mode and it is not working fineWhen you press  v ( for visual single characters) and then press the navigation keys ie h,l to select characterseither left or right   , selects the first character and remains stuck .Check it out    Στις Τρίτη, 8 Ιανουαρίου 2019, 11:28:02 π.μ. EET, ο χρήστης Alexey <notifications@github.com> έγραψε:  
 
 
@vakosel Pls test this issue. do you see it needs fixing more?

**Comment by Alexey-T** [comment]
We move new topic to #21
